name: Scheduled update

on:
  workflow_dispatch:
  schedule:
    # Every Monday at 1:00 UTC
    - cron: '0 1 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
          # Use a custom PAT to allow triggering other workflows
          token: ${{ secrets.PAT }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Commit
        env:
          # Use a custom PAT to allow triggering other workflows
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git config --local user.email ${{ secrets.GIT_EMAIL }}
          git config --local user.name ${{ vars.GIT_USERNAME }}
          # Read last tag and increment patch version
          echo Current version = $(git describe --tags --abbrev=0)
          export NEW_VERSION=$(git describe --tags --abbrev=0 | awk -F. '{OFS="."; $3=$3+1; print $0}')
          echo New version = $NEW_VERSION
          dotnet build
          git add Arcasharp.UserAgents/Generated/*
          if [ ! git diff-index --quiet HEAD ]; then
            echo "No changes"
            exit 0
          fi
          echo "Changes detected"
          git commit -m "build(update): user agents" --no-verify
          git tag $NEW_VERSION
          git push origin ${{ github.head_ref }}
          git push origin $NEW_VERSION
          
